nodejs:
  applicationPort: 3000
  autoscaling:
    enabled: false

postgresql:
  enabled: false
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
elastic:
  enabled: false
sscs-tribunals-api:
  enabled: false
sscs-tya-notif:
  enabled: false
sscs-tribunals-frontend:
  enabled: false
redis:
  enabled: false
ccd:
  enabled: false
em-ccdorc:
  enabled: false
sscs-hearings-api:
  enabled: false
servicebus:
  enabled: false
ccd-case-document-am-api:
  enabled: false
aac-manage-case-assignment:
  enabled: false
am-org-role-mapping-service:
  enabled: false
ccd-def-cleanup:
  enabled: false
job:
  #DO NOT DELETE, Below line is aliasing all values from Java settings above to job to avoid duplication.
  <<: *javavalues
  enabled: false